package com.bom.master.controller;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.bom.common.*; import com.bom.master.entity.*; import com.bom.master.mapper.*; import com.bom.integration.service.SapIntegrationService; import com.bom.system.auth.CurrentUser; import lombok.RequiredArgsConstructor; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import javax.servlet.http.HttpServletResponse; import java.io.*; import java.nio.charset.StandardCharsets; import java.time.LocalDateTime; import java.util.*;
@RestController @RequestMapping("/api/parts") @RequiredArgsConstructor
public class PartController {
 private final PartMapper parts; private final PartRevisionMapper revisions; private final PartDocumentMapper docs; private final CodeGenerator codes; private final SapIntegrationService sap;
 @GetMapping public R<Page<Part>> page(@RequestParam(defaultValue="1")long current,@RequestParam(defaultValue="20")long size,@RequestParam(required=false)String keyword,@RequestParam(required=false)String partType,@RequestParam(required=false)String category,@RequestParam(required=false)String lifecycle,@RequestParam(required=false)String makeBuy){QueryWrapper<Part> q=new QueryWrapper<>();q.and(keyword!=null&&!keyword.isEmpty(),w->w.like("part_no",keyword).or().like("part_name",keyword)).eq(partType!=null,"part_type",partType).eq(category!=null,"category",category).eq(lifecycle!=null,"lifecycle",lifecycle).eq(makeBuy!=null,"make_buy",makeBuy).orderByDesc("id");return R.ok(parts.selectPage(new Page<>(current,size),q));}
 @GetMapping("/{id}") public R<Part> get(@PathVariable Long id){return R.ok(parts.selectById(id));}
 @PostMapping public R<Part> create(@RequestBody Part x){x.setId(null);if(x.getPartNo()==null||x.getPartNo().trim().isEmpty())x.setPartNo(codes.next("P").replace("-","").substring(0,10));if(x.getRevision()==null)x.setRevision("A");if(x.getLifecycle()==null)x.setLifecycle("DRAFT");parts.insert(x);return R.ok(x);}
 @PutMapping("/{id}") public R<Part> update(@PathVariable Long id,@RequestBody Part x){x.setId(id);parts.updateById(x);return R.ok(parts.selectById(id));}
 @DeleteMapping("/{id}") public R<Void> delete(@PathVariable Long id){parts.deleteById(id);return R.ok();}
 @PostMapping("/{id}/submit") public R<Part> submit(@PathVariable Long id){return transition(id,"DRAFT","IN_REVIEW");}
 @PostMapping("/{id}/release") public R<Part> release(@PathVariable Long id){Part x=parts.selectById(id);if(x==null||!"IN_REVIEW".equals(x.getLifecycle()))throw new BizException("零件必须处于 IN_REVIEW");x.setLifecycle("RELEASED");parts.updateById(x);PartRevision r=new PartRevision();r.setPartId(id);r.setRevision(x.getRevision());r.setReleasedBy(CurrentUser.get()==null?null:CurrentUser.get().getUsername());r.setReleasedAt(LocalDateTime.now());revisions.insert(r);return R.ok(x);}
 @PostMapping("/{id}/obsolete") public R<Part> obsolete(@PathVariable Long id){return transition(id,"RELEASED","OBSOLETE");}
 @PostMapping("/{id}/revise") public R<Part> revise(@PathVariable Long id){Part old=parts.selectById(id);if(old==null||!"RELEASED".equals(old.getLifecycle()))throw new BizException("仅 RELEASED 可修订");Part n=new Part();org.springframework.beans.BeanUtils.copyProperties(old,n);n.setId(null);n.setRevision(nextRevision(old.getRevision()));n.setLifecycle("DRAFT");parts.insert(n);return R.ok(n);}
 @PostMapping("/{id}/sync-sap") public R<Part> sync(@PathVariable Long id){return R.ok(sap.syncPart(id));}
 @GetMapping("/{id}/documents") public R<List<PartDocument>> documents(@PathVariable Long id){return R.ok(docs.selectList(new QueryWrapper<PartDocument>().eq("part_id",id)));}
 @PostMapping("/{id}/documents") public R<PartDocument> addDoc(@PathVariable Long id,@RequestBody PartDocument x){x.setId(null);x.setPartId(id);docs.insert(x);return R.ok(x);}
 @DeleteMapping("/documents/{id}") public R<Void> delDoc(@PathVariable Long id){docs.deleteById(id);return R.ok();}
 @PostMapping("/import") public R<Integer> imp(@RequestParam("file") MultipartFile f)throws Exception{int n=0;try(BufferedReader r=new BufferedReader(new InputStreamReader(f.getInputStream(),StandardCharsets.UTF_8))){String s;boolean h=true;while((s=r.readLine())!=null){if(h){h=false;continue;}String[] a=s.split(",",-1);if(a.length>=3){Part p=new Part();p.setPartNo(a[0]);p.setRevision(a[1]);p.setPartName(a[2]);p.setLifecycle(a.length>3?a[3]:"DRAFT");parts.insert(p);n++;}}}return R.ok(n);}
 @GetMapping("/export") public void exp(HttpServletResponse res)throws Exception{res.setContentType("text/csv;charset=UTF-8");res.getWriter().println("partNo,revision,partName,lifecycle");for(Part p:parts.selectList(null))res.getWriter().println(String.join(",",safe(p.getPartNo()),safe(p.getRevision()),safe(p.getPartName()),safe(p.getLifecycle())));}
 private R<Part> transition(Long id,String from,String to){Part x=parts.selectById(id);if(x==null||!from.equals(x.getLifecycle()))throw new BizException("当前状态不允许操作");x.setLifecycle(to);parts.updateById(x);return R.ok(x);}
 private static String nextRevision(String r){if(r==null||r.isEmpty())return "A";return String.valueOf((char)(r.charAt(0)+1));} private static String safe(String s){return s==null?"":s.replace(","," ");}
}
