<template>
  <div class="page"><div class="page-title"><h2>{{ header.bomNo }} <el-tag>{{ header.status }}</el-tag></h2><el-button @click="$router.back()">返回</el-button></div><el-card shadow="never"><el-descriptions :column="4"><el-descriptions-item label="类型">{{ header.bomType }}</el-descriptions-item><el-descriptions-item label="版本">{{ header.version }}</el-descriptions-item><el-descriptions-item label="车型">{{ header.vehicleModelId }}</el-descriptions-item><el-descriptions-item label="工厂">{{ header.plantId }}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never" class="mt"><el-tabs v-model="tab" @tab-change="loadTab"><el-tab-pane label="结构树" name="tree"><el-table :data="tree" row-key="partId" stripe><el-table-column prop="level" label="层级" width="70" /><el-table-column prop="path" label="路径" /><el-table-column prop="partNo" label="零件号" /><el-table-column prop="partName" label="名称" /><el-table-column prop="qty" label="数量" /><el-table-column prop="extendedQty" label="累计数量" /><el-table-column prop="item.usageCondition" label="配置条件" /><el-table-column prop="item.stationCode" label="工位" /></el-table></el-tab-pane><el-tab-pane label="缩排展开" name="explode"><el-form inline><el-form-item label="层级"><el-input-number v-model="level" :min="1" :max="10" /></el-form-item></el-form><el-table :data="explode"><el-table-column prop="level" label="层级" /><el-table-column prop="partNo" label="零件号" /><el-table-column prop="partName" label="名称" /><el-table-column prop="extendedQty" label="累计数量" /></el-table></el-tab-pane><el-tab-pane label="汇总 BOM" name="summary"><el-table :data="summary"><el-table-column prop="partNo" label="零件号" /><el-table-column prop="partName" label="名称" /><el-table-column prop="extendedQty" label="汇总数量" /></el-table></el-tab-pane><el-tab-pane label="成本/重量" name="rollup"><el-statistic title="总成本" :value="roll.totalCost || 0" /><el-statistic title="总重量" :value="roll.totalWeight || 0" /><el-table :data="roll.details || []" class="mt"><el-table-column prop="partNo" label="零件号" /><el-table-column prop="extendedQty" label="数量" /></el-table></el-tab-pane><el-tab-pane label="配置 BOM" name="config"><el-form inline><el-form-item v-for="f in features" :key="f.id" :label="f.name"><el-select v-model="selections[f.feature]" clearable><el-option v-for="o in f.options" :key="o.id" :label="o.optionName" :value="o.optionCode" /></el-select></el-form-item><el-button type="primary" @click="configure">解析 100% BOM</el-button></el-form><el-alert v-if="configured" title="配置 BOM 解析成功" type="success" show-icon /><el-table :data="configured?.tree || []" class="mt"><el-table-column prop="partNo" label="零件号" /><el-table-column prop="extendedQty" label="累计数量" /></el-table></el-tab-pane><el-tab-pane label="按工位" name="station" v-if="header.bomType === 'MBOM'"><el-empty description="工位分组接口已预留" /></el-tab-pane><el-tab-pane label="导入/导出" name="csv"><el-alert title="支持 BOM 行 CSV 导入导出" type="info" /></el-tab-pane></el-tabs></el-card></div>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { boms, master } from '../../api'
const route = useRoute(); const $router = useRouter(); const header = ref({}); const tree = ref([]); const explode = ref([]); const summary = ref([]); const roll = ref({}); const tab = ref('tree'); const level = ref(3); const features = ref([]); const selections = ref({}); const configured = ref(null)
async function loadTab(name = tab.value) { if (name === 'tree') tree.value = await boms.tree(route.params.id); if (name === 'explode') explode.value = await boms.explode(route.params.id, level.value); if (name === 'summary') summary.value = await boms.summarized(route.params.id); if (name === 'rollup') roll.value = await boms.rollup(route.params.id); if (name === 'config') { features.value = await master.features(); for (const f of features.value) f.options = await master.options(f.id) } }
async function configure() { configured.value = await boms.action(route.params.id, 'configure', { selections: selections.value }) }
onMounted(async () => { header.value = await boms.get(route.params.id); await loadTab('tree') })
</script>
