<template>
  <div class="page"><div class="page-title"><h2>工作台</h2><el-button @click="load">刷新</el-button></div><el-row :gutter="16"><el-col v-for="c in cards" :key="c.label" :span="4"><div class="stat"><div class="label">{{ c.label }}</div><div class="value">{{ c.value }}</div></div></el-col></el-row><el-row :gutter="16" class="mt"><el-col :span="10"><el-card shadow="never"><template #header>零件生命周期分布</template><div v-for="x in lifecycle" :key="x.name" class="life-row"><span>{{ x.name }}</span><el-progress :percentage="x.percent" :format="() => `${x.count} 个`" /></div></el-card></el-col><el-col :span="14"><el-card shadow="never"><template #header>车型项目 EBOM / MBOM</template><el-table :data="data.vehicleModels || []" size="small"><el-table-column prop="modelCode" label="车型" /><el-table-column prop="modelName" label="名称" /><el-table-column prop="ebomStatus" label="EBOM"><template #default="{row}"><el-tag type="success">{{ row.ebomStatus || '暂无' }}</el-tag></template></el-table-column><el-table-column prop="mbomStatus" label="MBOM"><template #default="{row}"><el-tag type="success">{{ row.mbomStatus || '暂无' }}</el-tag></template></el-table-column></el-table></el-card></el-col></el-row><el-row :gutter="16" class="mt"><el-col :span="12"><el-card shadow="never"><template #header>最近集成日志</template><el-table :data="data.recentIntegrationLogs || []" size="small"><el-table-column prop="createdAt" label="时间" /><el-table-column prop="system" label="系统" /><el-table-column prop="action" label="动作" /><el-table-column prop="status" label="状态" /></el-table></el-card></el-col><el-col :span="12"><el-card shadow="never"><template #header>最近操作日志</template><el-table :data="data.recentOpLogs || []" size="small"><el-table-column prop="createdAt" label="时间" /><el-table-column prop="username" label="用户" /><el-table-column prop="path" label="路径" /></el-table></el-card></el-col></el-row></div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { dashboard } from '../api'
const data = ref({})
const cards = computed(() => [{ label: '零件数', value: data.value.partCount || 0 }, { label: 'RELEASED 零件', value: data.value.partsByLifecycle?.RELEASED || 0 }, { label: 'BOM 数', value: data.value.bomCount || 0 }, { label: '待审 ECR', value: data.value.pendingEcr || 0 }, { label: '待实施 ECN', value: data.value.pendingEcn || 0 }, { label: '本月发布零件', value: data.value.partsByLifecycle?.RELEASED || 0 }])
const lifecycle = computed(() => { const x = data.value.partsByLifecycle || {}; const total = Object.values(x).reduce((a, b) => a + b, 0) || 1; return Object.entries(x).map(([name, count]) => ({ name, count, percent: Math.round(count * 100 / total) })) })
async function load() { data.value = await dashboard.summary() }
onMounted(load)
</script>
